### ISSUE TITLE
 License violation 

### ISSUE THREAD

**Issue by mervick** [knottx/aes256-dart#1]
Hello,

I noticed that you have used code from my repository https://github.com/mervick/aes-everywhere in your repository https://github.com/knottx/aes256-dart without following the terms of the MIT license.

The MIT license requires that you include the original license and copyright notice in all copies or substantial portions of the software.

Could you please add the MIT license to your repository and attribute the original authorship as per the license terms?

Thank you for your understanding and cooperation.

**Comment by knottx** [comment]
@mervick Updated dbd06c9

**Comment by mervick** [comment]
Thank you
